server:
  port: 5555
spring:
  application:
    name: zuul-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true
zuul:
  routes:
    enter:
      path: /enters/**
      serviceId: enter-server
    getout:
      path: /getout/**
      serviceId: getout-server
  prefix: /api #路由前缀
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #熔断响应时间
ribbon:
  #熔断读取时间
  ReadTimeout: 60000
  #连接等待时间
  ConnectTimeout: 60000