server:
  port: 5555
spring:
  application:
    name: zuul-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myservers?characterEncoding=utf-8
    # sql is update
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true
zuul:
  routes:
    enter:
      path: /enters/**
      serviceId: enter-server
    getout:
      path: /getout/**
      serviceId: getout-server
  prefix: /api #路由前缀
  #错误响应配置时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #熔断响应时间
  #ribbon超时配置 读取和等待时间都设置6秒
ribbon:
  #熔断读取时间
  ReadTimeout: 60000
  #连接等待时间
  ConnectTimeout: 60000