server:
  port: 8763
spring:
  application:
    name: getout-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/myservers?characterEncoding=utf-8
          # sql is update
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
    #2秒向注册中心eureka发送心跳-如果没有发送即从注册中心剔除
    lease-expiration-duration-in-seconds: 2
    #1秒和注册中心交互发送心跳
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/