server:
  port: 8765
spring:
  application:
    name: elastic-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myservers?characterEncoding=utf-8
    # sql is update
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  data:
    elasticsearch:
      cluster-name: my-elasticsearch
      cluster-nodes: 127.0.0.1:9301,127.0.0.1:9302,127.0.0.1:9303
eureka:
  instance:
    hostname: localhost
    defaultZone:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/